### ISSUE TITLE
Missing build instructions in the README

### ISSUE THREAD

**Issue by binkley** [batect/batect.dev#1299]
This project, though documentation, should follow the same practices as other projects. Running `./batect build` complains that I don't have `docusaurus` installed. I checked the README, and did not see how to install. There is a link to the Docusaurus website, however, it would be nice for the README to have a "How to build" section.

**Comment by charleskorn** [comment]
Thanks for the feedback @binkley - I've added some instructions to the readme. Please take a look and let me know if there's anything else that would be helpful to add here.

**Comment by binkley** [comment]
Awesome @charleskorn !
Running `setup` before running `build` fixed my Docusaurus problem.
